test: add regression test for issue #775
filerjs/filer pull request #778
Opened 2021-04-18 13:33 UTC by bcheidemann

Adds a test which demonstrates issue #775

2021-04-18 15:48 UTC, humphd commented on tests/bugs/issue775.js
> +  it('should create a directory then call fs.readdir with options', function (done) {
If you add `.skip` here, we could land this and enable it when a fix comes in.

2021-04-18 16:08 UTC, humphd commented
Same deal here, this needs a rebase.

2021-05-23 10:56 UTC, bcheidemann commented
I've done a rebase here too but will probably need to redo once #777 is merged as there will likely be conflicts.

2021-05-23 12:25 UTC, bcheidemann commented
@humphd I've updated the readdir function to accept an options object - behaviour should be consistent with node fs.readdir except I haven't implemented the withFileTypes option yet. Will rename the pr and add WIP prefix.

2021-05-26 13:56 UTC, humphd requested changes
Do you want to rebase this to pick up the work in your other PRs that I just merged?

2021-05-29 11:22 UTC, bcheidemann commented
@humphd I've done a rebase and added implementation for handling the withFileTypes option. Should be good to merge if you're happy with it =)

2021-06-01 17:58 UTC, humphd requested changes
Looks good, nice work.

Can you update the README in this same PR for the `options` and `withFileTypes` additions?

2021-06-01 23:15 UTC, bcheidemann commented
> Looks good, nice work.
> 
> 
> 
> Can you update the README in this same PR for the `options` and `withFileTypes` additions?

No problem 👌

2021-06-05 17:09 UTC, bcheidemann commented
@humphd updated the README =)

2021-06-05 17:45 UTC, humphd approved these changes
Nice!

2021-06-05 17:45 UTC, merged